import './globals.css'
import toast, { Toaster } from 'react-hot-toast';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
        <Toaster containerStyle={{zIndex:1000000}}/>
      </body>
    </html>
  )
}
